version: "3"

services:
  postgres:
    image: postgres:12-alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: actix
      POSTGRES_PASSWORD: actix
      POSTGRES_DB: actix
    ports:
      - 5432:5432
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'

  actix-todos:
    build: .
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      SERVER.HOST: 0.0.0.0
      SERVER.PORT: 8080
      PG.USER: actix
      PG.PASSWORD: actix
      PG.HOST: postgres
      PG.PORT: 5432
      PG.DBNAME: actix
      PG.POOL.MAX_SIZE: 30
    ports:
      - 8080:8080
    deploy:
      resources:
        limits:
          memory: '512M'
          cpus: '1'
